zuul:
  retryable: true
  routes:
    shop:
      path: /shop/**
      serviceId: shop-service
    user:
      path: /user/**
      serviceId: user-service

spring:
  zipkin:
    baseUrl: http://localhost:9411/