spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: eunchong
    password: dmschd92
  cloud:
    stream:
      bindings:
        buyItemChannel:
          destination: buyItems
      default:
        contentType: application/json
  zipkin:
    baseUrl: http://localhost:9411/