spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: eunchong
    password: ****
  cloud:
    stream:
      bindings:
        input:
          destination: buyItems
          group: buyItemsQueue
  zipkin:
    baseUrl: http://localhost:9411/